float SCROLL_LEFT = SIDEBAR_X_OFFSET;
float SCROLL_RIGHT = WIDTH;
float SCROLL_HEIGHT = REC_HEIGHT/2;
public void drawScroll(float y_offset){
  fill(0,0,0);
  rect(SIDEBAR_X_OFFSET,0, CATEGORY_WIDTH + REC_WIDTH, REC_HEIGHT/2);
  if(y_offset > HEIGHT)
  rect(SIDEBAR_X_OFFSET,HEIGHT-REC_HEIGHT/2, CATEGORY_WIDTH + REC_WIDTH, REC_HEIGHT/2);
  fill(255,255,255);
  triangle(SIDEBAR_X_OFFSET + (CATEGORY_WIDTH + REC_WIDTH)/2, 5, SIDEBAR_X_OFFSET + (CATEGORY_WIDTH + REC_WIDTH)/2+5, 15, SIDEBAR_X_OFFSET + (CATEGORY_WIDTH + REC_WIDTH)/2-5, 15);
  if(y_offset > HEIGHT)
  triangle(SIDEBAR_X_OFFSET + (CATEGORY_WIDTH + REC_WIDTH)/2, HEIGHT-REC_HEIGHT/2+15, SIDEBAR_X_OFFSET + (CATEGORY_WIDTH + REC_WIDTH)/2+5, HEIGHT-REC_HEIGHT/2 +5, SIDEBAR_X_OFFSET + (CATEGORY_WIDTH + REC_WIDTH)/2-5, HEIGHT-REC_HEIGHT/2+5);
  
}

public boolean scrollUp(float x, float y){
  return x>=SCROLL_LEFT && x<SCROLL_RIGHT && y>=0 && y<SCROLL_HEIGHT; 
}

public boolean scrollDown(float x, float y){
 return x>=SCROLL_LEFT && x<SCROLL_RIGHT && y>=HEIGHT-SCROLL_HEIGHT && y<=HEIGHT; 
  
}
